name: robin_flutter
description: Robin Message SDK
version: 0.0.1
homepage:

environment:
  sdk: ">=2.15.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^1.0.0
  file_picker: ^4.3.0
  image_picker: ^0.8.4+4
  flutter_slidable: ^1.1.0
  intl: ^0.17.0
  url_launcher: ^6.0.17
  open_file: ^3.2.1
  cached_network_image: ^3.2.0
  string_validator: ^0.3.0
  http: ^0.13.4
  html: ^0.15.0
  linkify: ^4.1.0
  web_socket_channel: ^2.1.0
  shared_preferences: ^2.0.11
  shimmer: ^2.0.0
  get: ^4.6.1
  uuid: ^3.0.6
  fluttertoast: ^8.0.8
  jiffy: ^5.0.0
  flutter_ringtone_player: ^3.1.1
  path_provider: ^2.0.9
  record: ^3.0.2
  audioplayers: ^0.20.1
  animated_size_and_fade: ^3.0.0
  carousel_slider: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/fileTypes/
    - assets/images/reactions/
    - assets/icons/

  fonts:
    - family: Hanken
      fonts:
        - asset: assets/fonts/HankenGrotesk-Bold.ttf
        - asset: assets/fonts/HankenGrotesk-Light.ttf
          weight: 200
        - asset: assets/fonts/HankenGrotesk-Bold.ttf
          weight: 600